// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxNju4Exn_eAdmkKxKwZv0cTrM4BOQrs',
    appId: '1:84402331097:web:4d25fba01db6a0a428cdc8',
    messagingSenderId: '84402331097',
    projectId: 'seera-b44e4',
    authDomain: 'seera-b44e4.firebaseapp.com',
    storageBucket: 'seera-b44e4.firebasestorage.app',
    measurementId: 'G-B8QLHL3F66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH4TF50-7VTZOCo_ayCgdwsv4heqYKFUA',
    appId: '1:84402331097:android:5037a6f2aa9c837d28cdc8',
    messagingSenderId: '84402331097',
    projectId: 'seera-b44e4',
    storageBucket: 'seera-b44e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzuEUIP9dz89nu48lWpINno2dQTu5HA5U',
    appId: '1:84402331097:ios:977ce9444fb67f1228cdc8',
    messagingSenderId: '84402331097',
    projectId: 'seera-b44e4',
    storageBucket: 'seera-b44e4.firebasestorage.app',
    iosBundleId: 'com.ibrahim22khaled.seera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzuEUIP9dz89nu48lWpINno2dQTu5HA5U',
    appId: '1:84402331097:ios:977ce9444fb67f1228cdc8',
    messagingSenderId: '84402331097',
    projectId: 'seera-b44e4',
    storageBucket: 'seera-b44e4.firebasestorage.app',
    iosBundleId: 'com.ibrahim22khaled.seera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcxNju4Exn_eAdmkKxKwZv0cTrM4BOQrs',
    appId: '1:84402331097:web:30e01be2758ee63228cdc8',
    messagingSenderId: '84402331097',
    projectId: 'seera-b44e4',
    authDomain: 'seera-b44e4.firebaseapp.com',
    storageBucket: 'seera-b44e4.firebasestorage.app',
    measurementId: 'G-LDNHTBDSRP',
  );
}
